### ISSUE TITLE
Arabic QA - Mar 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#34]
### 1. My Bookmarks
<img width="372" alt="AR_MyBookmarks" src="https://user-images.githubusercontent.com/48343061/76674597-80353500-656e-11ea-8bc3-eb365e70bd2a.png">

### 2. Questionnaire - New Topics Recommended
![AR_NewTopics](https://user-images.githubusercontent.com/48343061/76674601-86c3ac80-656e-11ea-9b30-6e71d494f976.png)

### 3. Help
![Screen Shot 2020-03-13 at 9 07 30 PM](https://user-images.githubusercontent.com/48343061/76674649-0c475c80-656f-11ea-8a02-b0f0751a90e7.png)

### 4. Search Input
![Screen Shot 2020-03-13 at 9 11 06 PM](https://user-images.githubusercontent.com/48343061/76674663-2b45ee80-656f-11ea-926e-8d2eb1d348e5.png)

### 5a. Search Error - Invalid Location
![Screen Shot 2020-03-13 at 9 12 47 PM](https://user-images.githubusercontent.com/48343061/76674715-9c85a180-656f-11ea-9dac-f20dd98066da.png)

### 5b. Search Error - No Results
![Screen Shot 2020-03-13 at 9 12 16 PM](https://user-images.githubusercontent.com/48343061/76674704-88da3b00-656f-11ea-88f1-27544920cf79.png)

### 6. Search Results - Show More
![Screen Shot 2020-03-13 at 9 19 38 PM](https://user-images.githubusercontent.com/48343061/76674806-672d8380-6570-11ea-9ff0-bfa8480a9e6a.png)

### 7a. Service Detail 1
![Screen Shot 2020-03-13 at 9 21 12 PM](https://user-images.githubusercontent.com/48343061/76674836-af4ca600-6570-11ea-8d20-280f110ef2c6.png)

### 7b. Service Detail 2
![Screen Shot 2020-03-13 at 9 22 38 PM](https://user-images.githubusercontent.com/48343061/76674849-e91dac80-6570-11ea-8f75-a3b2bf4755f4.png)

**Comment by hhaboh** [comment]
Screen 1. My Bookmarks: Fail (1 issue)
Source text: No topics to show
Current text: لا توجد موضوعات كي نعرضها
Suggested text: لا توجد مواضيع كي نعرضها
Rationale: to ensure consistency with other instances in the app.

Screen 2. Questionnaire - New Topics Recommended: PASS

Screen 3. Help: PASS

Screen 4. Search Input: Fail (1 issue)
Source text: please call BC211.
Current text: يرجى اتصل بخدمة BC211.
Suggested text: يرجى الاتصال بخدمة BC211.
Rationale: To ensure grammatical correctness, since "call BC211" was translated as a standalone segment, not part of a full sentence.

Screen 5a. Search Error - Invalid Location: PASS

Screen 5b. Search Error - No Results: PASS

Screen 6. Search Results - Show More: PASS

Screen 7a. Service Detail 1: Fail (1 issue)
Source text: Provided by:
Current text: يقدمه لكم:
Suggested text: يقدمها لكم:
Rationale: To ensure gender agreement with the Arabic word for "service."

Screen 7b. Service Detail 2: PASS

**Comment by jparlina** [comment]
Created issue on GitHub frontend [issue #1068](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1068).

**Comment by jparlina** [comment]
See revised screenshots [here](https://docs.google.com/document/d/1V7nCQd4fLlFYERVzVIaAKDtq3QGEIS5pXazZS2XFspM/edit) and comment here on Github: **_PASS/FAIL_** (describe any issue using comment below)

### My Bookmarks - No Topics (see screenshot #5)
_**Your previous QA:**_
Source text: No topics to show
Current text: لا توجد موضوعات كي نعرضها
Suggested text: لا توجد مواضيع كي نعرضها
Rationale: to ensure consistency with other instances in the app.

_Note: Issues on Screen 4 and Screen 7a will be fixed with the next staging release (not part of this QA._

**Comment by hhaboh** [comment]
My Bookmarks - No Topics: PASS

**Comment by jparlina** [comment]
Fixed on Staging V1.29.0 Server V1.3.28: 

**Screen 4**
<img width="444" alt="Screen Shot 2020-04-21 at 5 44 24 PM" src="https://user-images.githubusercontent.com/48343061/79928483-ec217d80-83f7-11ea-8733-7dacad40c59c.png">

**Screen 7a** 
<img width="440" alt="Screen Shot 2020-04-21 at 5 46 41 PM" src="https://user-images.githubusercontent.com/48343061/79928591-2c80fb80-83f8-11ea-8e3d-762c6bf3e908.png">
