### ISSUE TITLE
Arabic QA: COVID-19 Information

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#46]
![IMG_4223](https://user-images.githubusercontent.com/48343061/77807228-74ed0980-7044-11ea-9c92-2534d245d6c1.jpeg)

**Comment by hhaboh** [comment]
Since I have no access to screenshots from the links provided (both browser and ISP block such links), I will use the staging app from TestFlight. My suggested text does not change anything, the only thing missing is space(s) between sentences.
This is the current screenshot: 
![IMG_0857](https://user-images.githubusercontent.com/50676567/77856464-438f4d80-71ac-11ea-92de-d3c7ee5cda9a.PNG)

English text: Many of our listed services are transitioning to alternate service delivery methods.
Please check service providers' websites for details.
Questions about COVID-19? Get the latest information from BC Centre for Disease Control.
Current text: عدد كبير من خدماتنا المدرجة ينتقل إلى سبل بديلة لتقديم الخدمات.يرجى زيارة المواقع الشبكة لمقدمي الخدمات كي تطلع على التفاصيل.
هل لديك أسئلة تتعلق بكوفيد-19؟طالع آخر المعلومات من مركز مكافحة الأمراض في بريتيش كولومبيا.
Suggested text: عدد كبير من خدماتنا المدرجة ينتقل إلى سبل بديلة لتقديم الخدمات. يرجى زيارة المواقع الشبكة لمقدمي الخدمات كي تطلع على التفاصيل.
هل لديك أسئلة تتعلق بكوفيد-19؟ طالع آخر المعلومات من مركز مكافحة الأمراض في بريتيش كولومبيا.

This is the same screenshot indicating the location of missing spaces
![IMG_0857 - edited_LI](https://user-images.githubusercontent.com/50676567/77856561-da5c0a00-71ac-11ea-9bb0-3ce514f5df21.jpg)

**Comment by jparlina** [comment]
Fixed on weblate. Jean to review after next staging release.

**Comment by jparlina** [comment]
Fixed on Staging V1.26.0, Server 1.3.25 

![Screen Shot 2020-04-03 at 3 22 43 PM](https://user-images.githubusercontent.com/48343061/78409740-467caa80-75bf-11ea-9164-afeeadc5a309.png)
