### ISSUE TITLE
French QA: App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#77]
### 1. Content Alert
![Screen Shot 2020-07-27 at 4 36 09 PM](https://user-images.githubusercontent.com/48343061/88602914-a264b680-d028-11ea-93de-45355f367a18.png)

### 2. Search - Street
![Screen Shot 2020-07-15 at 4 58 13 PM](https://user-images.githubusercontent.com/48343061/87611263-6b9faf80-c6bc-11ea-8d1d-922a78988d7e.png)

### 3. Search - Near
![Screen Shot 2020-07-16 at 6 12 07 PM](https://user-images.githubusercontent.com/48343061/87737484-f2718c80-c78f-11ea-88dd-b23ab148a719.png)

### 4. Feedback - Suggest an update
<img width="377" alt="Screen Shot 2020-08-03 at 9 02 22 PM" src="https://user-images.githubusercontent.com/48343061/89252377-656f6580-d5ce-11ea-828b-df386c5a198a.png">

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-15 at 5 11 23 PM](https://user-images.githubusercontent.com/48343061/87612399-4a8c8e00-c6bf-11ea-91dc-be4ce84b4fea.png)

### 6. Feedback - System Explainer (ALL)
![Screen Shot 2020-08-03 at 9 04 41 PM](https://user-images.githubusercontent.com/48343061/89252473-b41cff80-d5ce-11ea-93cd-f1432999e8e6.png)

### 7. Feedback - Thank You
![Screen Shot 2020-07-16 at 10 18 16 AM](https://user-images.githubusercontent.com/48343061/87702090-ce8d5700-c74d-11ea-867e-c2be355316c7.png)

### 8. Feedback - Other Suggestions
![Screen Shot 2020-07-16 at 1 42 07 PM](https://user-images.githubusercontent.com/48343061/87738400-25b51b00-c792-11ea-95da-e6f5e43188d8.png)

### 9. Feedback - Service No Longer Exists
![Screen Shot 2020-07-16 at 1 54 26 PM](https://user-images.githubusercontent.com/48343061/87738602-a07e3600-c792-11ea-8d17-21a41aeca9b2.png)

### 10. Feedback - Contact Info (ALL)
![Screen Shot 2020-07-16 at 9 05 02 PM](https://user-images.githubusercontent.com/48343061/87747385-0aeda100-c7a8-11ea-9e0a-08629d98e005.png)

### 11. Feedback - Form
![Screen Shot 2020-07-16 at 8 26 40 PM](https://user-images.githubusercontent.com/48343061/87745447-c4497800-c7a2-11ea-964d-41b6e5091c3e.png)

### 12. Open External Link
![Screen Shot 2020-07-16 at 8 32 59 PM](https://user-images.githubusercontent.com/48343061/87745781-af211900-c7a3-11ea-8fe4-8e51da492d76.png)

### 13. Onboarding 2
![Screen Shot 2020-07-16 at 8 50 01 PM](https://user-images.githubusercontent.com/48343061/87746651-f4464a80-c7a5-11ea-957b-5e529ce17900.png)

**Comment by ludivinegh** [comment]
**Issues:**

**(1) Screen Name: Content Alert**
English Texts: COVID-19 information
Current Texts: Informations relatives au COVID-19
Suggested Texts: Informations relatives à la COVID-19
Rationale: In fr-CA, COVID-19 is a feminine noun because "D" stands for disease. The mistake could have been made because "COVID-19" is masculine in fr-FR. Other instances on the screenshot are correct.

**(4) Screen Name: Feedback - Suggest an update**
English Texts: This service no longer exists
Current Texts: Ce service n'existe plus
Suggested Texts: Ce service n’existe plus
Rationale: This string uses a straight apostrophe while the rest of the app uses curly apostrophes (see for instance: https://drive.google.com/file/d/1boHcNXMV5LxZ7HaWE3nai-X64_nFQV9e/view?usp=drivesdk). I can see inconsistencies elsewhere. Would it be possible for you to search all straight apostrophes and replace them with a curly one (or the other way around) for consistency purposes? I can report the affected strings from this QA task, but a simple search and replace might be more efficient. We want to replace ' with ’.

**(6) Screen Name: Feedback - System Explainer**
English Texts: The Arrival Advisor team will work with bc211 to review your suggestions before we make the final changes.
Current Texts: L'équipe d'Arrival Advisor collaborera avec bc211 pour analyser vos suggestions avant de mettre en modifier les renseignements.
Suggested Texts: L’équipe d'Arrival Advisor collaborera avec bc211 pour analyser vos suggestions avant de modifier les renseignements.
Rationale: Please remove "mettre en", as it introduces a grammatical error. **Not reporting specific strings, but this screen uses straight apostrophes.** Please fix if possible, as per my previous comment.

**(10) Screen Name: Feedback - Contact Info** 
English Texts: Enter email address
Current Texts: Entrer l'adresse courriel
Suggested Texts: Entrez l'adresse courriel
Rationale: Imperative form preferred here, for consistency with the rest of the screen. Note that the current version is not incorrect and is inconsistent with similar strings on other screens also using the infinitive. Since the other strings on Feedback - Contact Info use the imperative because they directly address the user, I think it would be nice to update this one.

**(10) Screen Name: Feedback - Contact Info** 
English Texts: Do you work at this service or organization?
Current Texts: Travaillez-vous à ce service ou cette organisation?
Suggested Texts: Travaillez-vous dans ce service ou au sein de cet organisme?
Rationale: Incorrect preposition which doesn't work in context + terminology update as per other instances of "organization".

**(10) Screen Name: Feedback - Contact Info** 
English Texts: Organization
Current Texts: Organisations
Suggested Texts: Organisme
Rationale: The French version uses the plural form while it shouldn't. Although the translation is correct apart from this, I would suggest using the synonym "Organisme" as per the other screens and website screenshots.

**(12) Screen Name: Open External Link**
English Texts: Cancel
Current Texts: ANNULER
Suggested Texts: Annuler
Rationale: Capitalization mismatch - although this might be related to the phone's locale and not to the app. Fix if possible, otherwise it is fine. Also, the screen uses straight apostrophes. Please fix if possible as per my previous comments.

**No issues:**

(2) Search - Street - PASS
(3) Search - Near - PASS
(4) Feedback - Suggest an update - PASS
(5) Feedback - Discard Changes - PASS
(7) Feedback - Thank You - PASS
(8) Feedback - Other Suggestions - PASS
(9) Service No Longer Exists - PASS (except an apostrophe could be fixed)
(11) Feedback - Form - PASS
(13) Revised Onboarding 2 - PASS

**Summarizing where the apostrophes would need to be fixed below for clarity:**

Feedback - Suggest an update
Feedback - System Explainer
Open External Link
Service No Longer Exists

**Comment by jparlina** [comment]
### Amended Screenshots: 

### (1) Content Alert
![Screen Shot 2020-08-17 at 11 22 36 AM](https://user-images.githubusercontent.com/48343061/90430278-06085f80-e07c-11ea-82ee-f66c398a3885.png)

### (4) Feedback - Suggest an update
![Screen Shot 2020-08-17 at 11 20 43 AM](https://user-images.githubusercontent.com/48343061/90430327-1ae4f300-e07c-11ea-826f-260025049fbe.png)

### (6) Feedback - System Explainer
![Screen Shot 2020-08-17 at 11 28 05 AM](https://user-images.githubusercontent.com/48343061/90430991-31d81500-e07d-11ea-98d6-54fb544a15f1.png)

### (10) Feedback - Contact Info
![Screen Shot 2020-08-17 at 11 33 26 AM](https://user-images.githubusercontent.com/48343061/90431185-81b6dc00-e07d-11ea-8619-446b5b39ea63.png)

### (12) Open External Link
![Screen Shot 2020-08-17 at 11 35 00 AM](https://user-images.githubusercontent.com/48343061/90431492-fa1d9d00-e07d-11ea-9e74-7a7aa4b84028.png)

**Comment by ludivinegh** [comment]
1. Content Alert - PASS
4. Feedback - Suggest an update - PASS
6. Feedback - System Explainer - PASS
10. Feedback - Contact Info - PASS
12. Open External Link - PASS
