### ISSUE TITLE
French QA: Website - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#79]
### 1. FAQ - Info Source
<img width="1236" alt="Screen Shot 2020-08-05 at 3 28 24 PM" src="https://user-images.githubusercontent.com/48343061/89470621-1261f380-d731-11ea-8d27-a4cb4333bc86.png">

### 2. FAQ - To be listed
![Screen Shot 2020-07-15 at 1 35 48 PM](https://user-images.githubusercontent.com/47794846/87593301-1c4b8600-c6a0-11ea-8a33-055c9c360f7c.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-15 at 1 37 25 PM](https://user-images.githubusercontent.com/47794846/87593462-574db980-c6a0-11ea-9d06-153ba803f55d.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-15 at 1 38 57 PM](https://user-images.githubusercontent.com/47794846/87593606-8cf2a280-c6a0-11ea-8514-88b6d5b87c59.png)

### 5. Home - Available in your language
![Screen Shot 2020-07-15 at 1 41 03 PM](https://user-images.githubusercontent.com/47794846/87593773-d80cb580-c6a0-11ea-8587-44965b03f74f.png)

**Comment by ludivinegh** [comment]
**Issues:**

Screen Name: FAQ - Info Source
English Texts: The topics provided by Arrival Advisor currently all come from the Newcomers' Guide to British Columbia, a resource made possible...
Current Texts: Les sujets proposés par Arrival Advisor sont tous tirés du guide à l'intention des nouveaux arrivants en Colombie-Britannique , une ressource offerte...
Suggested Texts: Les sujets proposés par Arrival Advisor sont tous tirés du guide à l'intention des nouveaux arrivants en Colombie-Britannique, une ressource offerte...
Rationale: There is an extra space after the hyperlink and comma.

Screen Name: FAQ - Info Source
English Texts: If you have a resource you would like to share, Contact us
Current Texts: Si vous souhaitez partager une ressource, communiquez avec nous
Suggested Texts: Si vous souhaitez partager une ressource, communiquez avec nous.
Rationale: Missing a full stop after the URL.

Screen Name: FAQ - Info Source
The layout doesn't match the source. I personally think it looks better in French, so it may not be an issue. See here: https://drive.google.com/file/d/1P-1tWEmN52QuvVy1D31mn4JatT5gtjg5/view?usp=drivesdk.

Screen Name: FAQ - To be listed
English Texts: you can email updates@bc211.ca so the bc211 team...
Current Texts: vous pouvez envoyer un courriel à updates@bc211.capour que l'équipe de bc211...
Suggested Texts: vous pouvez envoyer un courriel à updates@bc211.ca pour que l'équipe de bc211...
Rationale: Missing space after the URL.

Screen Name: Home - Available in your language
Rationale: Because this will be on the home page, I think it could benefit from better line breaks. Please move the highlighted terms on the following line in both cases: https://drive.google.com/file/d/1y3eWaQ2QvQucdARd_GDyKfvsIjm1VYFT/view?usp=drivesdk.

**No issues:**

3. FAQ - Website Version - PASS
4. FAQ - Checkmarked & Bookmarked Topics - PASS

**Comment by tomy-pg** [comment]
Amended screenshots:

### 1 FAQ - Info Source
![Screen Shot 2020-08-13 at 10 39 22 AM](https://user-images.githubusercontent.com/47794846/90168098-7d26b680-dd51-11ea-8531-a7e4a11eae06.png)

### 2 FAQ - To be listed
![Screen Shot 2020-08-13 at 10 40 13 AM](https://user-images.githubusercontent.com/47794846/90168112-81eb6a80-dd51-11ea-8714-9631c9bbed59.png)

### 5 Home
![Screen Shot 2020-08-13 at 10 30 25 AM](https://user-images.githubusercontent.com/47794846/90168143-8adc3c00-dd51-11ea-9ee8-b13e2eb1a3cd.png)
